# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='section',
            new_name='sections',
        ),
    ]
