# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20170521_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status',
            name='web',
            field=models.BooleanField(default=False),
        ),
    ]
