# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20170524_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='web',
            new_name='webs',
        ),
    ]
